### ISSUE TITLE
新手有些小问题想请教一下

### ISSUE THREAD

**Issue by liuhq** [Debuffxb/ZAFU_DDUP#1]
您好，我入门js没多久，刚好想做个自动填写每日一报的功能，但不懂怎么抓取相应的数据，例如填报页面所对应的url（尝试过用fiddler抓包过，但就是抓不到这个页面）以及相应所需的数据（比如体温数据对应的字符串等）。
请问您能否教我一下如何抓取这些信息的？
_谢谢您！_

**Comment by Debuffxb** [comment]
如果是手机端每日一报的话fiddler能够抓到其他的数据吗 比如浏览器打开网页？
一般来说需要抓取的是按下提交按钮的时候所提交的数据。

**Comment by liuhq** [comment]
我在fiddler中点击提交按钮后看到的相关链接是 

> http://app.zafu.edu.cn/app/usergps/submit.jhtm 

关于你在js文件中写到的

> https://appui.zafu.edu.cn/vapp/yqdj/submit.jhtm

> https://appui.zafu.edu.cn/vapp/yqdj/latestData.jhtm

这两个链接我并没有找到……
是我抓取的方式不正确吗（哭笑）

——————————————————————

另，我非计算机专业的，只是业余在学习js，有挺多地方其实还不太懂，就比如这个抓取页面链接及处理……
我现在在想再写一个关于签到的js文件，然后通过 android js（集成node环境的apk打包工具）制作一个单纯每日一报和上课签到功能的app（毕竟学校软件启动速度慢和相关功能操作过于繁杂，而这两个功能可以说是最经常使用的）

**Comment by Debuffxb** [comment]
emmm 我这边猜是https的关系 你可以了解下相关软件抓取https的东西具体该怎么操作。
你上面那个截图中露出来token。可以考虑修改下或者删除。

**Comment by liuhq** [comment]
ok,我试试，谢谢你了

**Comment by liuhq** [comment]
成功解决，抓到了相关的url。原来Android7以上需要系统级的ca证书才能获取https，装了个Android5的模拟器就能抓到了。
